/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.8
 * Generated at: 2015-10-27 17:51:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.student;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class myPage_005fStudent_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\n");
      out.write("    <head>\n");
      out.write("    <link rel=\"stylesheet\" href=\"../css/main.css\" type=\"text/css\" />\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <title>åæ¤</title>\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\" src=\"http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js\"></script>\n");
      out.write("<script src=\"//code.jquery.com/jquery-1.11.0.min.js\"></script>\n");
      out.write("  <script src=\"//code.jquery.com/ui/1.11.0/jquery-ui.js\"></script>\n");
      out.write("  <link rel=\"stylesheet\" href=\"//code.jquery.com/ui/1.11.0/themes/smoothness/jquery-ui.css\">\n");
      out.write("\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\t$(function(){\n");
      out.write("\t\t$(\"#monthdown\").click(function () {\n");
      out.write("\t\t\tvar m =parseInt($(\"#month\").text(), 10);\n");
      out.write("\t\t\tif(m==1){\n");
      out.write("\t\t\t\tm=13;\n");
      out.write("\t\t\t\tvar y =parseInt($(\"#year1\").text(), 10);\n");
      out.write("\t\t\t\ty=y-1;\n");
      out.write("\t\t\t\t$(\"#year1\").text(y);\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\tm=m-1;\n");
      out.write("\t\t\t$(\"#month\").text(m);\n");
      out.write("\t\t});\n");
      out.write("\t});\n");
      out.write("\t$(function(){\n");
      out.write("\t\t$(\"#monthup\").click(function () {\n");
      out.write("\t\t\tvar m =parseInt($(\"#month\").text(), 10);\n");
      out.write("\t\t\tif(m==12){\n");
      out.write("\t\t\t\tm=0;\n");
      out.write("\t\t\t\tvar y =parseInt($(\"#year1\").text(), 10);\n");
      out.write("\t\t\t\ty=y+1;\n");
      out.write("\t\t\t\t$(\"#year1\").text(y);\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\tm=m+1;\n");
      out.write("\t\t\t$(\"#month\").text(m);\n");
      out.write("\t\t});\n");
      out.write("\t});\n");
      out.write("\t$(function(){\n");
      out.write("\t\t$(\"#yeardown\").click(function () {\n");
      out.write("\t\t\tvar y =parseInt($(\"#year\").text(), 10);\n");
      out.write("\t\t\ty=y-1;\n");
      out.write("\t\t\t$(\"#year\").text(y);\n");
      out.write("\t\t});\n");
      out.write("\t});\n");
      out.write("\t$(function(){\n");
      out.write("\t\t$(\"#yearup\").click(function () {\n");
      out.write("\t\t\tvar y =parseInt($(\"#year\").text(), 10);\n");
      out.write("\t\t\ty=y+1;\n");
      out.write("\t\t\t$(\"#year\").text(y);\n");
      out.write("\t\t});\n");
      out.write("\t});\n");
      out.write("\t$(function() {\n");
      out.write("\t    $( \"#tabhoge\" ).tabs();\n");
      out.write("\t  });\n");
      out.write("\t\n");
      out.write("\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("<script src=\"../js/Chart.min.js\"></script>\n");
      out.write("\n");
      out.write("</head>\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../include/include1.jsp", out, true);
      out.write("\n");
      out.write("\n");
      out.write("<div id=\"side-left\">>> ãã¤ãã¼ã¸<br><br>\n");
      out.write("        <input type=\"submit\" value=\"ã¯ã©ã¹ãå¤æ´\" class=\"attendancebtn\" style=\"width:250px\">\n");
      out.write("        <br><br>\n");
      out.write("\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../include/include_teachericon.jsp", out, true);
      out.write("\n");
      out.write("        </div>\n");
      out.write("        \t<div id=\"main\">\n");
      out.write("        \t\n");
      out.write("        \t\t<div class=\"box class_attendstate\">\n");
      out.write("        \t\t<form name=\"js\">\n");
      out.write("        \t\t<br><br>\n");
      out.write("        \t\t\t<table id=\"student_attend\" >\n");
      out.write("        \t\t\t\t<tr>\n");
      out.write("        \t\t\t\t\t<td></td>\n");
      out.write("        \t\t\t\t\t<td colspan=\"2\"></td>\n");
      out.write("        \t\t\t\t\t<td></td>\n");
      out.write("        \t\t\t\t\t<td style=\"width:80px;text-align:center;border-left: 1px solid #000;border-bottom: 1px solid #000;\">ç¡å±</td>\n");
      out.write("        \t\t\t\t\t<td style=\"width:80px;text-align:center;border-left: 1px solid #000;border-bottom: 1px solid #000;\">å±åº</td>\n");
      out.write("        \t\t\t\t\t<td style=\"width:80px;text-align:center;border-left: 1px solid #000;border-bottom: 1px solid #000;\">éå»</td>\n");
      out.write("        \t\t\t\t\t<td style=\"width:80px;text-align:center;border-left: 1px solid #000;border-bottom: 1px solid #000;\">æ¬ èª²</td>\n");
      out.write("        \t\t\t\t\t<td style=\"width:80px;text-align:center;border-left: 1px solid #000;border-bottom: 1px solid #000;\">æ©é</td>\n");
      out.write("        \t\t\t\t\t<td style=\"width:80px;text-align:center;border-left: 1px solid #000;border-bottom: 1px solid #000;\">ã¿ãªã</td>\n");
      out.write("        \t\t\t\t\t<td style=\"width:80px;text-align:center;border-left: 1px solid #000;border-bottom: 1px solid #000;\">å¬æ¬ </td>\n");
      out.write("        \t\t\t\t\t<td style=\"width:80px;text-align:center;border-left: 1px solid #000;border-bottom: 1px solid #000;\">åºå¸­æ¥</td>\n");
      out.write("        \t\t\t\t\t<td style=\"width:80px;text-align:center;border-left: 1px solid #000;border-bottom: 1px solid #000;\">ç´¯è¨</td>\n");
      out.write("        \t\t\t\t</tr>\n");
      out.write("        \t\t\t\t<tr>\n");
      out.write("        \t\t\t\t\t<th style=\"border:none;border-left: 1px solid #000;border-top: 1px solid #000;\">\n");
      out.write("\t\t\t\t<input type=\"button\" id=\"monthdown\" value=\"â\">\n");
      out.write("\t\t\t</th>\n");
      out.write("\t\t\t<th colspan=\"2\" style=\"border:none;border-top: 1px solid #000;width:100px;\">\n");
      out.write("\t\t\t\t<h2>\n");
      out.write("\t\t\t\t\t<p id=\"year1\">2015</p>å¹´<br>\n");
      out.write("\t\t\t\t</h2>\n");
      out.write("\t\t\t</th>\n");
      out.write("\t\t\t<th style=\"border:none;border-top: 1px solid #000;\">\n");
      out.write("\t\t\t\t<input type=\"button\" id=\"monthup\" value=\"â¶\">\n");
      out.write("\t\t\t</th>\n");
      out.write("\t\t\t\t\t\t\t<td style=\"width:80px;text-align:center;border-left: 1px solid #000;\">ç¡å±</td>\n");
      out.write("        \t\t\t\t\t<td style=\"width:80px;text-align:center;border-left: 1px solid #000;\">å±åº</td>\n");
      out.write("        \t\t\t\t\t<td style=\"width:80px;text-align:center;border-left: 1px solid #000;\">éå»</td>\n");
      out.write("        \t\t\t\t\t<td style=\"width:80px;text-align:center;border-left: 1px solid #000;\">æ¬ èª²</td>\n");
      out.write("        \t\t\t\t\t<td style=\"width:80px;text-align:center;border-left: 1px solid #000;\">æ©é</td>\n");
      out.write("        \t\t\t\t\t<td style=\"width:80px;text-align:center;border-left: 1px solid #000;\">ã¿ãªã</td>\n");
      out.write("        \t\t\t\t\t<td style=\"width:80px;text-align:center;border-left: 1px solid #000;\">å¬æ¬ </td>\n");
      out.write("        \t\t\t\t\t<td style=\"width:80px;text-align:center;border-left: 1px solid #000;\">åºå¸­æ¥</td>\n");
      out.write("        \t\t\t\t\t<td style=\"width:80px;text-align:center;border-left: 1px solid #000;\">ç´¯è¨</td>\n");
      out.write("        \t\t\t\t</tr>\n");
      out.write("        \t\t\t\t\n");
      out.write("        \t\t\t\t\n");
      out.write("        \t\t\t</table>\n");
      out.write("        \t\t\t\n");
      out.write("        \t\t\t<br><br>\n");
      out.write("        \t\t\t\n");
      out.write("        \t\t\t<div id=\"tabhoge\" style=\"width:897px;margin-left:30px;\">\n");
      out.write("        \t\t\t<br><br>\n");
      out.write("    <ul>\n");
      out.write("      <li><a href=\"#t-1\">åæ</a></li>\n");
      out.write("      <li><a href=\"#t-2\">ä¸­æ</a></li>\n");
      out.write("      <li><a href=\"#t-3\">å¾æ</a></li>\n");
      out.write("    </ul>\n");
      out.write("\n");
      out.write("    <div id=\"t-1\">\n");
      out.write("    <table id=\"student_attend\" >\n");
      out.write("        \t\t\t\t<tr>\n");
      out.write("        \t\t\t\t\t<td></td>\n");
      out.write("        \t\t\t\t\t<td colspan=\"2\"></td>\n");
      out.write("        \t\t\t\t\t<td></td>\n");
      out.write("        \t\t\t\t\t<td style=\"width:80px;text-align:center;border-left: 1px solid #000;border-bottom: 1px solid #000;\">ç¡å±</td>\n");
      out.write("        \t\t\t\t\t<td style=\"width:80px;text-align:center;border-left: 1px solid #000;border-bottom: 1px solid #000;\">å±åº</td>\n");
      out.write("        \t\t\t\t\t<td style=\"width:80px;text-align:center;border-left: 1px solid #000;border-bottom: 1px solid #000;\">éå»</td>\n");
      out.write("        \t\t\t\t\t<td style=\"width:80px;text-align:center;border-left: 1px solid #000;border-bottom: 1px solid #000;\">æ¬ èª²</td>\n");
      out.write("        \t\t\t\t\t<td style=\"width:80px;text-align:center;border-left: 1px solid #000;border-bottom: 1px solid #000;\">æ©é</td>\n");
      out.write("        \t\t\t\t\t<td style=\"width:80px;text-align:center;border-left: 1px solid #000;border-bottom: 1px solid #000;\">ã¿ãªã</td>\n");
      out.write("        \t\t\t\t\t<td style=\"width:80px;text-align:center;border-left: 1px solid #000;border-bottom: 1px solid #000;\">å¬æ¬ </td>\n");
      out.write("        \t\t\t\t\t<td style=\"width:80px;text-align:center;border-left: 1px solid #000;border-bottom: 1px solid #000;\">åºå¸­æ¥</td>\n");
      out.write("        \t\t\t\t\t<td style=\"width:80px;text-align:center;border-left: 1px solid #000;border-bottom: 1px solid #000;\">ç´¯è¨</td>\n");
      out.write("        \t\t\t\t</tr>\n");
      out.write("        \t\t\t\t<tr>\n");
      out.write("        \t\t\t\t\t<th style=\"border:none;border-left: 1px solid #000;border-top: 1px solid #000;\">\n");
      out.write("\t\t\t\t<input type=\"button\" id=\"monthdown\" value=\"â\">\n");
      out.write("\t\t\t</th>\n");
      out.write("\t\t\t<th colspan=\"2\" style=\"border:none;border-top: 1px solid #000;width:100px;\">\n");
      out.write("\t\t\t\t<h2>\n");
      out.write("\t\t\t\t\t<p id=\"year1\">2015</p>å¹´<br>\n");
      out.write("\t\t\t\t</h2>\n");
      out.write("\t\t\t</th>\n");
      out.write("\t\t\t<th style=\"border:none;border-top: 1px solid #000;\">\n");
      out.write("\t\t\t\t<input type=\"button\" id=\"monthup\" value=\"â¶\">\n");
      out.write("\t\t\t</th>\n");
      out.write("\t\t\t\t\t\t\t<td style=\"width:80px;text-align:center;border-left: 1px solid #000;\">ç¡å±</td>\n");
      out.write("        \t\t\t\t\t<td style=\"width:80px;text-align:center;border-left: 1px solid #000;\">å±åº</td>\n");
      out.write("        \t\t\t\t\t<td style=\"width:80px;text-align:center;border-left: 1px solid #000;\">éå»</td>\n");
      out.write("        \t\t\t\t\t<td style=\"width:80px;text-align:center;border-left: 1px solid #000;\">æ¬ èª²</td>\n");
      out.write("        \t\t\t\t\t<td style=\"width:80px;text-align:center;border-left: 1px solid #000;\">æ©é</td>\n");
      out.write("        \t\t\t\t\t<td style=\"width:80px;text-align:center;border-left: 1px solid #000;\">ã¿ãªã</td>\n");
      out.write("        \t\t\t\t\t<td style=\"width:80px;text-align:center;border-left: 1px solid #000;\">å¬æ¬ </td>\n");
      out.write("        \t\t\t\t\t<td style=\"width:80px;text-align:center;border-left: 1px solid #000;\">åºå¸­æ¥</td>\n");
      out.write("        \t\t\t\t\t<td style=\"width:80px;text-align:center;border-left: 1px solid #000;\">ç´¯è¨</td>\n");
      out.write("        \t\t\t\t</tr>\n");
      out.write("        \t\t\t\t\n");
      out.write("        \t\t\t\t\n");
      out.write("        \t\t\t</table>\n");
      out.write("        \t\t\t\n");
      out.write("        \t\t\n");
      out.write("    </div>\n");
      out.write("    <div id=\"t-2\">\n");
      out.write("    </div>\n");
      out.write("    <div id=\"t-3\">\n");
      out.write("    </div>\n");
      out.write("    </div>\n");
      out.write("        \t\t</form>\n");
      out.write("        \t\t</div>\n");
      out.write("        \t</div>\n");
      out.write("        \t\n");
      out.write("        \t        \n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../include/include2.jsp", out, true);
      out.write("\n");
      out.write("</html>\n");
      out.write("        \t\t\t\t\t");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
